### ISSUE TITLE
Request for Source Code Access for ESP32 IR Gun Project

### ISSUE THREAD

**Issue by sam2024hanze** [mhfalken/esp32_ir_gun#1]
Hello 
I came across your ESP32 IR Gun project on GitHub, and I’m very impressed with the work you’ve done. I’m currently working on a similar project and believe that studying your source code could help me learn more about implementing IR communication and ESP32 programming.

Would it be possible for you to share the source code for this project? I fully understand if it’s not publicly available, but any guidance or insight would be greatly appreciated.

Thank you very much for your time and for sharing your project on GitHub.

**Comment by mhfalken** [comment]
Hi
Currently I have no plan for sharing the source code. The ESP32 has hardware support for IR (partial), but their software is unstable (at least in the software version I am using), so it is not easy to give any guidance about how to use it, as I had to make some hacks to get it stable. This is a know problem with ESP32. The hardware implementation is also different between the various chip versions, which doesn't makes it easier!
/Michael
